### ISSUE TITLE
rs_replace_table error: Forbidden (HTTP 403)

### ISSUE THREAD

**Issue by niklasvm** [sicarul/redshiftTools#39]
Hi there

Great package, thank you!

I am receiving an error when using:

```r
rs_replace_table(
  df = df,
  dbcon = rs,
  table_name = 'my_schema.rs_test',
  bucket = 's3://mybucket/',
  split_files = 1
)
```
Note: i have anonymised the S3 bucket and redshift schema.

Output:
```
Initiating Redshift table replacement for table my_schema.rs_test
The provided data.frame has 36 rows
Uploading 1 files with prefix cxcuowiijlrghzkaydkwwfkuttqzrtfotsdhzoiqoonjtuiqka to bucket s3://mybucket/
Error in { : task 1 failed - "Forbidden (HTTP 403)."
```

I think I have found the issue which is that my S3 bucket requires server side encryption to be set. I have used the `aws.s3` package before and usually just pass
```r
headers = c(`x-amz-server-side-encryption` = "AES256")
```
to `put_object`

Any thoughts? I'm happy to open a PR with a potential fix.

**Comment by sicarul** [comment]
@niklasvm Hey Niklas, thanks for reporting this! If i understand correctly, this exact same error appears when doing put_object with aws.s3 if you don't specify that header? Maybe as a general solution to this error, we could allow the redshift functions to send arbitrary headers for the s3 upload, WDYT?

**Comment by niklasvm** [comment]
It turns out I was specifying the bucket incorrectly and adding the headers didn't make a difference. I was using `s3://mybucket` instead of `mybucket`. The code runs further now but bugs out at the redshift `COPY` command:
```
Warning message:
In value[[3L]](cond) :
  Failed to fetch row: ERROR:  AWS session token not found
DETAIL:  
  -----------------------------------------------
  error:  AWS session token not found
  code:      8001
  context:   
  query:     14794383
  location:  aws_credentials_parser.cpp:150
  process:   padbmaster [pid=2257]
  -----------------------------------------------
```

I only pass a `key` and `secret` so the `session` token isn't required. It completes successfully if I exclude the token for the case where `session` is empty. Will open a PR

**Comment by lsabreu96** [comment]
hello, @niklasvm !

I'm still new to connecting R with databases, so sorry in advance not being able to follow the discussion above. I've been running into about the same issue as you last wrote, which is:

Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).
In addition: Warning message:
In value[[3L]](cond) :
  RS-DBI driver: (could not Retrieve the result : ERROR:  AWS session token not found
DETAIL:  
  error:  AWS session token not found
  code:      8001
  context:   
  query:     1448900
  location:  aws_credentials_parser.cpp:150
  process:   padbmaster [pid=32334]
  


Before I was running just into: 

Error in parse_aws_s3_response(r, Sig, verbose = verbose) :  Forbidden (HTTP 403). 

but I was still able to upload my databases, now the database is still uploaded but no rows appear when I call the database. Can you please shed a light on this, please?

p.s.: if you could please recommend me some reading on this, to better debug such issues, I'd appreciate it very much

**Comment by niklasvm** [comment]
Hi there. I narrowed the issue down to the redshift unload query. I have opened a PR with a fix that resolved it. Feel tree to give my fix a test: https://github.com/niklasvm/redshiftTools/tree/bug/redshift-copy-session

**Comment by niklasvm** [comment]
PR here: https://github.com/sicarul/redshiftTools/pull/40

**Comment by lsabreu96** [comment]
Hi, there
Didn't work, actually I was using rs_create_table like so (sry for the confusion):

rs_create_table(df = df,
                dbcon = conn,
                table_name = "table_name",
                bucket = "my-bucket",
                region = "region",
                access_key = "access_key",
                secret_key = "secret_key",
                split_files = 4)

Yesterday the script was running properly, today, after I updated the packages, this error you mentioned started appearing :(

**Comment by niklasvm** [comment]
Both `rs_create_table` and `rs_replace_table` use the same underlying logic. Your table would have created successfully but bugged out when trying to actually copy the data into the table. Have you tried to install my proposed update using:
```r
devtools::install_github('niklasvm/redshiftTools@bug/redshift-copy-session')
```

Then try again

**Comment by sicarul** [comment]
Fixed with Niklas' contribution, the PR is merged!

**Comment by tsydorenko** [comment]
Hi there, I installed redshiftTools today via devtools::install_github("sicarul/redshiftTools") and have the same issue with rs_create_table as mentioned above:

```
Initiating Redshift table replacement for table mytable12
The provided data.frame has 10000 rows and 2 columns
Uploading 4 files with prefix vegrxvmpcqdmytjnvoahtsbnhdfcayqlfolfxiuybfhzjecjwx to bucket tp-rtb-bid-requests
Upload to S3 complete!                                                                                                                                           
Deleting temporary files from S3 bucket
Deleting 4 files with prefix vegrxvmpcqdmytjnvoahtsbnhdfcayqlfolfxiuybfhzjecjwx from bucket tp-rtb-bid-requests
[1] FALSE                                                                                                                                                        
Warning message:
In value[[3L]](cond) :
  Failed to fetch row: ERROR:  AWS session token not found
DETAIL:  
  -----------------------------------------------
  error:  AWS session token not found
  code:      8001
  context:   
  query:     39076263
  location:  aws_credentials_parser.cpp:150
  process:   padbmaster [pid=31559]
  -----------------------------------------------
```

**Comment by lsabreu96** [comment]
@niklasvm 
I tried using your PR but the issue kept appearing.
updated the package after the merge as well, but the error persists

**Comment by niklasvm** [comment]
> @niklasvm
> I tried using your PR but the issue kept appearing.
> updated the package after the merge as well, but the error persists

Your error must be linked to something else then. Are you using a session token?

**Comment by lsabreu96** [comment]
Hm, no, I'm not.
Just the acess key and secret access key used to work. 
Sorry for verbiage below, as I'm still new to R, this whole is still not clear to me. The flow should then be:
1)open connection
2)use get_session_token and store it
3)pass it within create table?

Many thanks in advance for the patience

**Comment by sicarul** [comment]
@lsabreu96 can you provide some example code of the issue you are seeing to understand how you are calling the process? This fix is not yet in CRAN, so you will need to install from github:

`devtools::install_github('sicarul/redshiftTools')`

Thanks

**Comment by lsabreu96** [comment]
@sicarul , sure thing !

`install.packages("aws.ec2metadata", repos = c(cloudyr = "http://cloudyr.github.io/drat",` `getOption("repos")))`

`install.packages(c('devtools', 'httr', 'aws.s3', 'Rcpp', 'DBI'))`

`library(RPostgreSQL)`
`library(redshiftTools)`
`library(RPostgres)`

`devtools::install_github("sicarul/redshiftTools")`

`drv <- dbDriver("PostgreSQL")`

`pconn_rsql <- dbConnect(drv,
                         host = "host",
                         port = port,
                         user = "user",
                         password = "password",
                         dbname = "dbname")`

`rs_create_table(df = mtcars,
            dbcon = conn,
            table_name = "table_name",
            bucket = "my-bucket",
            region = "region",
            access_key = "acess-key",
            secret_key = "secret-key",
            split_files = 4)`

`dbDisconnect(pconn_rsql)`

Much appreciate the help

P.S.: haven't tried calling with session token yet 'cause I'm still not sure which comand gives the session token and where I should call it

**Comment by sicarul** [comment]
Hey @lsabreu96 i'm an idiot, i had merged the PR into the dev branch instead of master. Can you retry installing now?

You do not need the session token.

**Comment by lsabreu96** [comment]
No problem.
Just reinstalled it. It works! The database is being written.
I keep receiving the following error tho
'List of 4
 $ Code     : chr "AccessDenied"
 $ Message  : chr "Access Denied"
 $ RequestId: chr "DD7723771034D043"
 $ HostId   : chr "reiUv/SkZuvOOmrEOsxU1lFAkL/zdBkgwED6plMuGcGzHDOSW01ib5i+if4zfJgu1SdbBNuQVyQ="
 - attr(*, "headers")=List of 6
  ..$ x-amz-request-id : chr "DD7723771034D043"
  ..$ x-amz-id-2       : chr "reiUv/SkZuvOOmrEOsxU1lFAkL/zdBkgwED6plMuGcGzHDOSW01ib5i+if4zfJgu1SdbBNuQVyQ="
  ..$ content-type     : chr "application/xml"
  ..$ transfer-encoding: chr "chunked"
  ..$ date             : chr "Tue, 28 May 2019 12:12:21 GMT"
  ..$ server           : chr "AmazonS3"
  ..- attr(*, "class")= chr [1:2] "insensitive" "list"
 - attr(*, "class")= chr "aws_error"
NULL
Error in parse_aws_s3_response(r, Sig, verbose = verbose) : 
  Forbidden (HTTP 403).'

**Comment by lsabreu96** [comment]
hey sicarul, no problem
It works ! The database is being now properly written. 
I keep receiving the following  tho:
`Error in parse_aws_s3_response(r, Sig, verbose = verbose) : Forbidden (HTTP 403).`

As far as I'm concerned, this is not an issue, since the base is being written. Just wanted to give a heads up.
Thanks a lot for all the help and the support

**Comment by niklasvm** [comment]
> hey sicarul, no problem
> It works ! The database is being now properly written.
> I keep receiving the following tho:
> `Error in parse_aws_s3_response(r, Sig, verbose = verbose) : Forbidden (HTTP 403).`
> 
> As far as I'm concerned, this is not an issue, since the base is being written. Just wanted to give a heads up.
> Thanks a lot for all the help and the support

Just double check the data is actually loading because in my case it appeared to work when I got that same error message but after checking the table, the data hadn't copied

**Comment by lsabreu96** [comment]
it did copied !
I checked it

before I got the issue with the session token, I was still getting this error message, but able to write the data

**Comment by sicarul** [comment]
Hey @lsabreu96 maybe that error appears because you have access to read/write but not delete data in the bucket?
The package deletes the data that it wrote on the bucket after copying to redshift to avoid keeping the data there.

**Comment by lsabreu96** [comment]
I see!
Thanks a lot for all the help, @sicarul  
:)

**Comment by cvanvelt** [comment]
Hi, I have installed redshiftTools via devtools::install_github("sicarul/redshiftTools") and still have the issue as described above.

rs_create_table(ctx_hip_meta, dbcon=db, table_name='metadata', bucket="bucket", split_files=10, session_token="")
Initiating Redshift table creation for table metadata
Initiating Redshift table replacement for table metadata
The provided data.frame has 1490596 rows
Uploading 10 files with prefix kvbeamoucgqowroinbrhdflufsmejxqsnasqjkgvgzqtimzbjx to bucket bucket
Upload to S3 complete!                                             
Deleting temporary files from S3 bucket
Deleting 10 files with prefix kvbeamoucgqowroinbrhdflufsmejxqsnasqjkgvgzqtimzbjx from bucket bucket
[1] FALSE                                                          
Warning message:
In value[[3L]](cond) :
  Failed to fetch row: ERROR:  AWS session token not found
DETAIL:  
  -----------------------------------------------
  error:  AWS session token not found
  code:      8001
  context:   
  query:     236599
  location:  aws_credentials_parser.cpp:150
  process:   padbmaster [pid=28949]
  -----------------------------------------------

if I add a session_token it works fine, but without I keep running into an error. I would rather not have to generate a new token each time it expires.
